name: Take Screenshot

on:
  push:
    branches:
      - master

jobs:
  screenshot-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Take Screenshot
        run: |
          Add-Type -AssemblyName System.Windows.Forms
          $bounds = [System.Windows.Forms.SystemInformation]::VirtualScreen
          $bitmap = New-Object Drawing.Bitmap $bounds.Width, $bounds.Height
          $graphics = [Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.Size)
          $screenshotPath = "screenshot.png"
          $bitmap.Save($screenshotPath, [Drawing.Imaging.ImageFormat]::Png)

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-windows
          path: screenshot.png

  screenshot-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Take Screenshot
        run: |
          screencapture -x screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-macos
          path: screenshot.png

  screenshot-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y scrot xvfb

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Take Screenshot
        run: |
          export DISPLAY=:99
          scrot screenshot.png

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-ubuntu
          path: screenshot.png